### ISSUE TITLE
From SMILES code: minimizestructures

### ISSUE THREAD

**Issue by k0ryphae** [jvermaas/LigninBuilder#5]
So I ran in vmd:
::ligninbuilder::minimizestructures output namd2 "+p8" "parameters extraparameters.prm \n parameters toppar/par_all36_cgenff.prm \n"

(made a few corrections because in this form the script won't find extraparameters.prm and par_all36_cgenff.prm: I put ../ in front of them)

Now Tkconsole yields: molecule contains no frames

copy of terminal window:

Info) Using plugin psf for structure file output/L.psf
psfplugin) WARNING: no impropers defined in PSF file.
psfplugin) no cross-terms defined in PSF file.
Info) Analyzing structure ...
Info)    Atoms: 428
Info)    Bonds: 445
Info)    Angles: 764  Dihedrals: 1013  Impropers: 0  Cross-terms: 0
Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
Info)    Residues: 15
Info)    Waters: 0
Info)    Segments: 1
Info)    Fragments: 1   Protein: 0   Nucleic: 0
Info) Using plugin pdb for coordinates from file output/L.pdb
Info) Finished with coordinate file output/L.pdb.
psfplugin) Structure requires space-delimited NAMD PSF format
psfplugin) Writing angles/dihedrals/impropers...
Info) Opened coordinate file output/L.psf for writing.
Info) Finished with coordinate file output/L.psf.
Info) Opened coordinate file output/L.pdb for writing.
Info) Finished with coordinate file output/L.pdb.
Info) Analyzing Volume...
Info)    Grid size: 64x62x56  (3 MB)
Info)    Total voxels: 222208
Info)    Min: 0.000000  Max: 25.733103  Range: 25.733103
Info)    Computing volume gradient map for smooth shading
Info) Added volume data, name=density newvol
Info) Using plugin namdbin for coordinates from file output/out.coor
Info) Finished with coordinate file output/out.coor.
ERROR
 molecule contains no frames

**Comment by jvermaas** [comment]
What version of VMD? There is a known issue with the current VMD 1.9.4 alpha builds, where they create a new molecule when you generate a new volume map. If you use VMD 1.9.3, this issue doesn't pop up.

**Comment by k0ryphae** [comment]
Yes you are correct, it's 1.9.4. Sorry for inconvinience.

**Comment by jvermaas** [comment]
Coolios! Glad to have gotten that sorted. I've got a patch outstanding with the VMD devs to fix this behavior, but it hasn't been incorporated into the VMD mainline.

**Comment by k0ryphae** [comment]
> Coolios! Glad to have gotten that sorted. I've got a patch outstanding with the VMD devs to fix this behavior, but it hasn't been incorporated into the VMD mainline.

Thanks alot! I am very interested in your enormous body of work about lignin simulations. I'm trying to replicate parts of one of your recent publication "Molecular Lignin Solubility and Structure in Organic solvents" in ACS Sustainable Chemistry & Engineering but due to my lack of understanding of NAMD/VMD, specifically force field parameters etc., I am very interested how you utilize tools you have created or helped to create (TopoTools inside VMD) to take the simulation part into GROMACS (of which I have more knowledge about). I'm having a few errors when converting the topology into format GROMACS can read. Is there a better way to correspond, if you agree to that, perhaps your provided e-mail adress or it is fine for you if I post under here?

**Comment by jvermaas** [comment]
Emails directly to me aren't scalable, since there is only one of me, and tons of people that want to simulate systems. For lignin stuff, I'd be happy to talk on a limited basis to see where our research overlaps are in terms of putting together research collaborations, but in terms of tech support, I only do that in public forums like this one. That way, others can benefit when they have a question that they put into google. I have been known to answer specific questions on VMD-L and NAMD-L, particularly as they relate to TopoTools or LigninBuilder, so that might also be a good place to ask questions. However, this does mean that you need to do a bit of the legwork in documenting what your error is and how you got there, since when you say "I'm having a few errors", I don't know how to help. See https://raspi.tv/2017/how-to-ask-for-and-receive-technical-help-on-the-internet
